package xdm.core.media.muxer.transmux.es

import xdm.core.media.muxer.transmux.sample.Codec
import xdm.core.media.muxer.transmux.sample.Sample
import xdm.core.media.muxer.transmux.sample.Track

/**
 * AAC reader for ADTS-framed streams (TS stream_type 0x0F). Each ADTS frame becomes one MP4
 * sample of 1024 audio samples. The ADTS header is stripped (MP4 stores raw AAC) and an
 * AudioSpecificConfig is synthesized for the esds box. Timestamps are generated by counting
 * frames from the first PES PTS, which yields gapless audio; a large PTS jump re-anchors.
 */
class AdtsReader(private val sink: SampleSink) : ElementaryStreamReader {
    override val track = Track(Codec.AAC)

    private var nextPtsTicks = Long.MIN_VALUE
    private var configured = false

    override fun consume(data: ByteArray, offset: Int, length: Int, pts: Long, dts: Long) {
        val end = offset + length
        var i = offset

        // Convert the PES 90 kHz PTS into audio-timescale ticks once we know the sample rate.
        var pesAnchor = pts

        while (i + 7 <= end) {
            // Sync: 0xFFFx
            if ((data[i].toInt() and 0xFF) != 0xFF || (data[i + 1].toInt() and 0xF0) != 0xF0) {
                i++
                continue
            }
            val protectionAbsent = data[i + 1].toInt() and 0x01
            val profile = (data[i + 2].toInt() and 0xC0) shr 6           // audioObjectType - 1
            val freqIndex = (data[i + 2].toInt() and 0x3C) shr 2
            val channelConfig = ((data[i + 2].toInt() and 0x01) shl 2) or ((data[i + 3].toInt() and 0xC0) shr 6)
            val frameLength = ((data[i + 3].toInt() and 0x03) shl 11) or
                ((data[i + 4].toInt() and 0xFF) shl 3) or
                ((data[i + 5].toInt() and 0xE0) shr 5)
            if (frameLength < 7 || i + frameLength > end) break

            if (!configured) {
                configure(profile, freqIndex, channelConfig)
                configured = true
            }
            val sampleRate = track.sampleRate
            if (sampleRate <= 0) break

            // (Re)anchor timestamps at the first frame of a PES carrying a PTS.
            if (pesAnchor >= 0 && nextPtsTicks == Long.MIN_VALUE) {
                nextPtsTicks = pesAnchor * sampleRate / 90000L
            } else if (pesAnchor >= 0) {
                val expected = pesAnchor * sampleRate / 90000L
                if (kotlin.math.abs(expected - nextPtsTicks) > 2L * SAMPLES_PER_FRAME) {
                    nextPtsTicks = expected
                }
                pesAnchor = -1 // only re-anchor on first frame of the PES
            }
            if (nextPtsTicks == Long.MIN_VALUE) nextPtsTicks = 0

            val headerLen = if (protectionAbsent == 1) 7 else 9
            val rawLen = frameLength - headerLen
            if (rawLen > 0) {
                val fileOffset = sink.writeSampleData(data, i + headerLen, rawLen)
                track.samples.add(Sample(fileOffset, rawLen, nextPtsTicks, nextPtsTicks, true))
                nextPtsTicks += SAMPLES_PER_FRAME
            }
            i += frameLength
        }
    }

    override fun finish() {}

    private fun configure(profile: Int, freqIndex: Int, channelConfig: Int) {
        val audioObjectType = profile + 1
        track.sampleRate = if (freqIndex < SAMPLE_RATES.size) SAMPLE_RATES[freqIndex] else 44100
        track.channelCount = if (channelConfig in 1..7) CHANNELS[channelConfig] else channelConfig
        track.timescale = track.sampleRate
        // AudioSpecificConfig: AOT(5) | freqIndex(4) | channelConfig(4) | GASpecificConfig(3) = 16 bits.
        val asc = ByteArray(2)
        asc[0] = ((audioObjectType shl 3) or (freqIndex shr 1)).toByte()
        asc[1] = (((freqIndex and 0x1) shl 7) or (channelConfig shl 3)).toByte()
        track.audioSpecificConfig = asc
    }

    companion object {
        const val SAMPLES_PER_FRAME = 1024L
        val SAMPLE_RATES = intArrayOf(
            96000, 88200, 64000, 48000, 44100, 32000, 24000, 22050,
            16000, 12000, 11025, 8000, 7350, 0, 0, 0
        )
        val CHANNELS = intArrayOf(0, 1, 2, 3, 4, 5, 6, 8)
    }
}
